import { OrderItem, PlatterSize } from "./orderModels";

/**
 * @swagger
 * components:
 *   schemas:
 *     OrderCreateRequest:
 *       type: object
 *       description: Request body for creating a new order
 *       required:
 *         - customerName
 *         - customerPhoneNumber
 *         - platterSize
 *         - items
 *         - pickupDate
 *         - pickupTime
 *       properties:
 *         customerName:
 *           type: string
 *           description: Full name of the customer placing the order
 *           example: "Shohei Ohtani"
 *         customerPhoneNumber:
 *           type: string
 *           description: Customer's contact phone number
 *           example: "204-616-5050"
 *         platterSize:
 *           type: number
 *           enum: [12, 36, 50, 75, 100]
 *           description: Size of the order platter
 *           example: 36
 *         items:
 *           type: array
 *           description: List of products to include in the order
 *           items:
 *             $ref: '#/components/schemas/OrderItem'
 *         pickupDate:
 *           type: string
 *           format: date
 *           description: Date when customer will pick up order (YYYY-MM-DD format)
 *           example: "2026-04-25"
 *         pickupTime:
 *           type: string
 *           format: time
 *           description: Time when customer will pick up order (HH:mm format)
 *           example: "2:00 PM"
 *         totalPrice:
 *           type: number
 *           description: Total price of the order (optional, calculated by backend)
 *           example: 10
 *         status:
 *           type: string
 *           enum: ["Pending"]
 *           description: Order status at creation (always Pending)
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: Timestamp when order was created (generated by backend)
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: Timestamp when order was last updated (generated by backend)
 */
export interface OrderCreateRequest {
    customerName: string;
    customerPhoneNumber: string;
    platterSize: PlatterSize;
    items: OrderItem[];
    pickupDate: string;
    pickupTime: string;
    totalPrice?: number;
    status: "Pending"; 
    createdAt?: Date;
    updatedAt?: Date;
}